#!/usr/bin/env bash

usage() {
    echo >&2 "${0##*/} [-c HOME_MANAGER_CONFIG]"
    exit 2
}

home_config=
while getopts c:h opt; do
    case "$opt" in
        c)
            home_config="$OPTARG"
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

scriptdir="$(cd "$(dirname "$0")" && pwd -P)"
PATH="$scriptdir/scripts:$PATH"

# shellcheck source=./components/common.sh
. "$scriptdir/components/common.sh" || exit 1

set -euo pipefail

if [ "$(id -u)" = "0" ]; then
    die "Error: Do not run as root, this script is for user setup"
fi

# Clone my dotfiles
DOTFILES_DIR=${DOTFILES_DIR:-$HOME/.dotfiles}
if ! [ -e "$DOTFILES_DIR" ]; then
    git clone https://github.com/kergoth/dotfiles "$DOTFILES_DIR"
fi
if ! [ -e "$DOTFILES_DIR/vim" ]; then
    git clone https://github.com/kergoth/dotvim "$DOTFILES_DIR/vim"
fi

if [ -n "$OS" ] && [ -e "$scriptdir/components/$OS/setup" ]; then
    # shellcheck disable=SC1090
    . "$scriptdir/components/$OS/setup"
else
    msg "WARNING: unrecognized or unsupported operating system"
fi

if command -v nix-env >/dev/null 2>&1; then
    msg "Applying Nix Home Manager configuration"
    "$scriptdir/switch.sh" ${home_config:+"$home_config"}
else
    msg "WARNING: nix is not installed, skipping home-manager setup"
fi

if [ -n "$OS" ] && [ -e "$scriptdir/components/$OS/post-setup" ]; then
    # shellcheck disable=SC1090
    . "$scriptdir/components/$OS/post-setup"
fi

msg "Setup complete"
