#!/bin/sh

# shellcheck source=./components/common.sh
. "$(dirname "$0")/components/common.sh" || exit 1

export HOMEBREW_PREFIX=${HOMEBREW_PREFIX:-~/.brew}
PATH="$HOMEBREW_PREFIX/bin:$(dirname "$0")/scripts:$PATH"

## Install CLI apps

if has pacman; then
    # Update package databases
    pacman_install -y
fi

# Baseline, and git for homebrew and asdf
if has apt-get; then
    sudo apt-get -y install build-essential git
elif has pacman; then
    pacman_install base-devel git
fi

# Install brew
if ! [ -e "$HOMEBREW_PREFIX/bin/brew" ]; then
    install-brew -s "$HOMEBREW_PREFIX"
fi

# Install languages
# shellcheck source=./scripts/install-asdf
. "$(dirname "$0")/scripts/install-asdf" || exit 1

# shellcheck source=./scripts/install-langs-asdf
"$(dirname "$0")/scripts/install-langs-asdf"

if has apt-get; then
    cat setup \
        | grep '^brew install' \
        | awk '{print $3}' \
        | grep -Ev 'ninja|fd|gh|git-delta|shfmt' \
        | xargs -t sudo apt-get -y install
    sudo apt-get -y install ninja-build fd-find
fi

# Not available via apt
brew install gh
brew install git-delta
brew install shfmt
