#!/bin/bash

set -euo pipefail

scriptdir="$(cd "$(dirname "$0")" && pwd -P)"

XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
# shellcheck disable=SC2086
export HOMEBREW_PREFIX=${HOMEBREW_PREFIX:-$HOME/.brew}
PATH="$HOMEBREW_PREFIX/bin:$XDG_DATA_HOME/../bin:$scriptdir/scripts:$PATH"

# shellcheck source=./components/common.sh
. "$scriptdir/components/common.sh" || exit 1

if [ "$(id -u)" = "0" ]; then
    die "Error: Do not run as root"
fi

if [ -z "$HOMEBREW_PREFIX" ]; then
    die "HOMEBREW_PREFIX must be set or unset, not the empty string"
fi

msg "Applying Nix Home Manager configuration"
"$scriptdir/switch.sh"

if is_mac; then
    if ! [ -x "$HOMEBREW_PREFIX/bin/brew" ]; then
        msg "Installing homebrew"
        install-brew -s "$HOMEBREW_PREFIX" || {
            rm -rf "$HOMEBREW_PREFIX"
            die "Failed to install homebrew"
        }
    fi

    msg "Installing applications with homebrew"
    "$HOMEBREW_PREFIX/bin/brew" bundle <"$scriptdir/Brewfile"
fi

msg "Configuring"
# shellcheck source=./components/macos-configure.sh
"$scriptdir/components/macos-configure.sh"
# shellcheck source=./components/macos-setup-apps.sh
"$scriptdir/components/macos-setup-apps.sh"

msg "Setup complete"
