#!/bin/bash

scriptdir="$(cd "$(dirname "$0")" && pwd -P)"
PATH="$scriptdir/scripts:$PATH"

HOMEBREW_PREFIX=${ADMIN_HOMEBREW_PREFIX:-${HOMEBREW_PREFIX:-$HOME/.brew}}

# shellcheck source=./components/common.sh
. "$scriptdir/components/common.sh" || exit 1

set -euo pipefail

if [ "$(id -u)" = "0" ]; then
    die "Error: Do not run as root, this script expects to use sudo if needed"
else
    need_sudo
fi

if [ -z "$HOMEBREW_PREFIX" ]; then
    die "HOMEBREW_PREFIX must be set or unset, not the empty string"
fi

if [ -n "$OS" ] && [ -e "$scriptdir/components/$OS/setup-admin" ]; then
    # shellcheck disable=SC1090
    . "$scriptdir/components/$OS/setup-admin"
else
    msg "WARNING: unrecognized or unsupported operating system"
fi
