#!/usr/bin/env bash

# User shell should be zsh
if [ -e /bin/zsh ] && [ "$(getent passwd "$(id -un)" | awk -F : '{print $NF}')" != /bin/zsh ]; then
    msg "Changing user shell to zsh"
    sudorun chsh -s /bin/zsh "$LOGNAME"
fi
