#!/usr/bin/env bash

# User shell should be zsh
if [ -e /bin/zsh ] && [ "$(getent passwd "$(id -un)" | awk -F : '{print $NF}')" != /bin/zsh ]; then
    msg "Changing user shell to zsh"
    # Failure is ignored here, as in some cases the user password might not be
    # known or set, as is the case with some container usage.
    chsh -s /bin/zsh || :
fi

# Install PowerShell modules, if needed
if has pwsh; then
    # Ignore failure, as these are not critical to my workflow, and can fail due
    # to transient network issues.
    pwsh -nop "./scripts/install-pwsh-modules.ps1" || :
fi
