#!/bin/sh

set -eu

has() {
    command -v "$1" >/dev/null 2>&1
}

run () {
    if has printcmd; then
        printf '❯ %s\n' "$(printcmd "$@")" >&2
    else
        printf '❯ %s\n' "$*" >&2
    fi
    "$@"
}

# shellcheck disable=SC3028,SC2034
case "${OSTYPE:-}" in
darwin*)
    OS=macos
    ;;
*)
    case "$(uname -r)" in
    *Microsoft | *microsoft*)
        OSTYPE=WSL
        ;;
    esac

    if [ -e /etc/os-release ]; then
        OS="$(sed -n -e 's/^ID=//p' /etc/os-release | tr '[:upper:]' '[:lower:]')"
    fi
    ;;
esac

if ! has git || ! has bash; then
    if [ "$OS" = freebsd ]; then
        if ! doas pkg -N; then
            run doas pkg bootstrap
        fi
        if ! command -v git >/dev/null 2>&1; then
            run doas env ASSUME_ALWAYS_YES=YES pkg install git
        fi
        if ! command -v bash >/dev/null 2>&1; then
            run doas env ASSUME_ALWAYS_YES=YES pkg install bash
        fi
    elif has nix-shell; then
        exec nix-shell -p git bash --run "$0"
    else
        echo >&2 "Error: unsupported host and git and/or bash are not available, exiting"
        exit 1
    fi
fi

SETUP_DIR=${SETUP_DIR:-$HOME/.setup}

if ! [ -e "$SETUP_DIR" ]; then
    run git clone --recursive https://github.com/kergoth/system-setup "$SETUP_DIR"
fi

run "$SETUP_DIR/setup-admin" || :
if [ -d /data/kergoth ]; then
    run "$SETUP_DIR/setup" -c work_data
elif [ -d /mel/kergoth ]; then
    run "$SETUP_DIR/setup" -c work
else
    run "$SETUP_DIR/setup"
fi
