#!/usr/bin/env bash

repodir="$(dirname "$(cd "$(dirname "$0")" && pwd -P)")"
PATH="$repodir/scripts:$PATH"

HOMEBREW_PREFIX=${ADMIN_HOMEBREW_PREFIX:-${HOMEBREW_PREFIX:-$HOME/.brew}}

# shellcheck source=../components/common.sh
. "$repodir/components/common.sh" || exit 1

set -euo pipefail

if [ "$(id -u)" = "0" ]; then
    die "Error: Do not run as root, this script expects to use sudo if needed"
else
    need_sudo
fi

if [ -z "$HOMEBREW_PREFIX" ]; then
    die "HOMEBREW_PREFIX must be set or unset, not the empty string"
fi

component_source "$repodir" setup-admin
component_source "$repodir" post-setup-admin

msg "Admin setup complete"
