#!/bin/bash

if ! [ -x "$HOMEBREW_PREFIX/bin/brew" ]; then
    msg "Installing homebrew"
    install-brew -s "$HOMEBREW_PREFIX" || {
        rm -rf "$HOMEBREW_PREFIX"
        die "Failed to install homebrew"
    }
fi

msg "Installing applications with homebrew"
# shellcheck disable=SC2154
"$HOMEBREW_PREFIX/bin/brew" bundle install --file="$scriptdir/components/macos/Brewfile"

msg "Configuring"
# shellcheck source=./components/macos/configure
"$scriptdir/components/macos/configure"
# shellcheck source=./components/macos/setup-apps
"$scriptdir/components/macos/setup-apps"
