#!/usr/bin/env bash

if ! [ -x "$HOMEBREW_PREFIX/bin/brew" ]; then
    msg "Installing homebrew"
    install-brew -s "$HOMEBREW_PREFIX" || {
        rm -rf "$HOMEBREW_PREFIX"
        die "Failed to install homebrew"
    }
fi

msg "Installing applications with homebrew"
unset HOMEBREW_AUTO_UPDATE

# shellcheck disable=SC2154
"$HOMEBREW_PREFIX/bin/brew" bundle --no-upgrade install --file="$scriptdir/components/macos/Brewfile"

msg "Configuring"
# shellcheck source=./configure
. "$scriptdir/../components/macos/configure"
# shellcheck source=./setup-apps
. "$scriptdir/../components/macos/setup-apps"

msg "Configuring complete"
