#!/bin/bash

if ! [ -x "$HOMEBREW_PREFIX/bin/brew" ]; then
    msg "Installing homebrew"
    install-brew -s "$HOMEBREW_PREFIX" || {
        rm -rf "$HOMEBREW_PREFIX"
        die "Failed to install homebrew"
    }
fi

msg "Installing applications with homebrew"
# shellcheck disable=SC2154
"$HOMEBREW_PREFIX/bin/brew" bundle <"$scriptdir/Brewfile.admin"

CASKROOM="$("$HOMEBREW_PREFIX/bin/brew" --caskroom)"
if [ -d "$CASKROOM"/whatsyoursign ]; then
    find "$CASKROOM"/whatsyoursign -name WhatsYourSign\ Installer.app -print0 \
        | xargs -0 open
fi

install-oversight

# Configuration
# shellcheck source=./components/macos-configure-admin.sh
"$scriptdir/components/macos-configure-admin.sh"
