#!/bin/sh

set -e

XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
xdg_root="$(dirname "${XDG_DATA_HOME:-$HOME/.local/share}")"
PIPX_HOME="${PIPX_HOME:-$xdg_root/pipx/venvs}"

python3 -m ensurepip --user --upgrade
python3 -m venv "$PIPX_HOME/pipx"

(
    # shellcheck disable=SC1091
    . "$PIPX_HOME/pipx/bin/activate"
    python3 -m pip install --disable-pip-version-check pipx
)
"$PIPX_HOME/pipx/bin/pipx" install --force pipx

mkdir -p "$xdg_root/bin"
ln -sf "$PIPX_HOME/pipx/bin/pipx" "$xdg_root/bin"
