#!/bin/bash

pacman () {
    sudorun pacman --noconfirm --needed "$@"
}

pacman -Sy

if ! pacman -Q nix >/dev/null 2>&1; then
    pacman -S nix
fi

sudorun systemctl enable nix-daemon
sudorun systemctl start nix-daemon
if ! grep -q "^nix-users:.*$USER" /etc/group; then
    sudorun sed -i -e "/^nix-users:/s/\$/ $USER/" /etc/group
    if ! grep -q "^nix-users:.*$USER" /etc/group; then
        echo >&2 "Failed to add user to the nix-users group, please do so manually, then re-login and re-run the setup-admin script"
    else
        echo >&2 "User has been added to the nix-users group, please re-login and re-run the setup-admin script"
    fi
    exit 1
fi

# for f in etc/profile.d/nix-daemon.sh etc/profile.d/nix.sh etc/profile.d/hm-session-vars.sh; do
#     for profile_dir in ~/.nix-profile \
#                     /nix/var/nix/profiles/per-user/$USER/profile \
#                     /nix/var/nix/profiles/default; do
#         if [ -e "$profile_dir/$f" ]; then
#             # shellcheck disable=SC1090
#             . "$profile_dir/$f"
#             break
#         fi
#     done
# done

# nix-channel --add https://nixos.org/channels/nixpkgs-unstable
# nix-channel --update

