#!/bin/bash

NIXPKGS=${NIXPKGS:-https://nixos.org/channels/nixpkgs-unstable}

pacman() {
    sudorun pacman --noconfirm --needed "$@"
}

install_nix() {
    if [ "$OSTYPE" = WSL ]; then
        sh <(curl -L https://nixos.org/nix/install) --no-daemon
    else
        pacman -S nix

        if ! grep -q "^nix-users:.*$USER" /etc/group; then
            sudorun sed -i -e "/^nix-users:/s/\$/ $USER/; /^nix-users:/s/: /:/;" /etc/group
            if ! grep -q "^nix-users:.*$USER" /etc/group; then
                echo >&2 "Failed to add user to the nix-users group, please do so manually, then re-login"
            else
                echo >&2 "User has been added to the nix-users group, please re-login"
            fi
        fi

        sudorun systemctl enable nix-daemon
        sudorun systemctl start nix-daemon
    fi

    # shellcheck disable=SC1090
    for i in ~/.nix-profile/etc/profile.d/nix-daemon.sh ~/.nix-profile/etc/profile.d/nix.sh; do
        if [ -e "$i" ]; then
            . "$i"
        fi
    done

    if [ -n "$NIXPKGS" ]; then
        nix-channel --add "$NIXPKGS" nixpkgs
        nix-channel --update
    fi
}

pacman -Sy

# Sync the files database
pacman -Fy

pacman -S openssh
if [ "$OSTYPE" != WSL ]; then
    sudorun systemctl enable sshd && sudo systemctl start sshd
fi

if ! grep -q '^MAKEFLAGS=.*-j' /etc/makepkg.conf; then
    CPUS=$(grep -c processor /proc/cpuinfo)
    JOBS=$((CPUS * 3 / 2))
    sudorun sed -i -e "s,#*MAKEFLAGS=.*,MAKEFLAGS=\"-j$JOBS\"," /etc/makepkg.conf
    if ! grep -q '^MAKEFLAGS=.*-j' /etc/makepkg.conf; then
        echo >&2 "Warning: failed to set MAKEFLAGS=-j$JOBS in /etc/makepkg.conf"
    fi
fi

if [ "$OSTYPE" != WSL ]; then
    pacman -S nss-mdns avahi
    sudorun sed -i -e '/hosts:/{ s/mdns_minimal //g; s/dns/mdns_minimal dns/; }' /etc/nsswitch.conf
    if ! grep -q 'hosts:.*mdns_minimal' /etc/nsswitch.conf; then
        echo >&2 "Warning: failed to add mdns_minimal to hosts resolution in /etc/nsswitch.conf"
    fi
    sudorun systemctl enable avahi-daemon.service
    sudorun systemctl start avahi-daemon.service || true
fi

pacman -S vi

# Clean up
if command pacman -Q nano >/dev/null 2>&1; then
    sudorun pacman --noconfirm -R nano
fi

install_nix
