#!/bin/bash

pacman () {
    sudorun pacman --noconfirm --needed "$@"
}

pacman -Sy

if ! pacman -Q nix >/dev/null 2>&1; then
    pacman -S nix
fi

sudorun systemctl enable nix-daemon
sudorun systemctl start nix-daemon
if ! grep -q "^nix-users:.*$USER" /etc/group; then
    sudorun sed -i -e "/^nix-users:/s/\$/ $USER/; /^nix-users:/s/: /:/;" /etc/group
    if ! grep -q "^nix-users:.*$USER" /etc/group; then
        echo >&2 "Failed to add user to the nix-users group, please do so manually, then re-login"
    else
        echo >&2 "User has been added to the nix-users group, please re-login"
    fi
    exit 1
fi
