#!/bin/sh

for i in ~/.nix-profile/etc/profile.d/*.sh; do
    if [ -e "$i" ]; then
        . "$i"
    fi
done

if [ -n "$NIXRUN" ] || [ -d /nix ]; then
    # Avoid failures due to nix-user-chroot nesting
    exec "$@"
else
    export NIXRUN=1
    exec nix-user-chroot ~/.nix "$@"
fi
